import Carte from "../modeles/Carte";
import Categorie from "../modeles/Categorie";

const cartes: Carte[] = [
    { categorie: Categorie.aide, cycle: "Déplacement", description: "Rejoue!", titre: "Encore!" },
    { categorie: Categorie.aide, cycle: "Déplacements", description: "Avance d'une case.", titre: "Manque d'inspiration" },
    { categorie: Categorie.aide, cycle: "Déplacements", description: "Échange de place avec le joueur de ton choix.", titre: "Merci d'avoir gardé ma place" },
    { categorie: Categorie.aide, cycle: "Déplacements", description: "Échange de place avec le premier joueur.", titre: "Moi d'abord" },

    { categorie: Categorie.chaos, cycle: "Bibi Party", description: "Jusqu'à ton prochain tour, les dés déplacent de la moitié du nombre de cases supposé, arrondi en haut.", titre: "Dé empoisonné" },
    { categorie: Categorie.chaos, cycle: "Bibi Party", description: "Jusqu'à ton prochain tour, les lancers dés font reculer les pions.", titre: "Cul-de-sac" },
    { categorie: Categorie.chaos, cycle: "Garde cette carte", description: "Utilise cette carte quand tu veux pour doubler la conséquence de quelqu'un. La récompense est aussi doublée.", titre: "Portions doubles" },
    { categorie: Categorie.chaos, cycle: "Garde cette carte", description: "Utilise cette carte quand tu veux pour faire piger une nouvelle conséquence à quelqu'un.", titre: "Non merci!" },
    { categorie: Categorie.chaos, cycle: "Garde cette carte", description: "Utilise cette carte quand tu veux pour réussir gratuitement une conséquence qui t'es assignée.", titre: "Oui merci!" },
    { categorie: Categorie.chaos, cycle: "Réorganisation", description: "Réorganisez les pions pour que les joueurs avec les récipients les plus pleins soient en avant.", titre: "Bande d'assoiffés" },
    { categorie: Categorie.chaos, cycle: "Réorganisation", description: "Réorganisez les pions pour que les joueurs avec les récipients les plus vides soient avant.", titre: "Bande d'ivrognes" },
    { categorie: Categorie.chaos, cycle: "Réorganisation", description: "Tous les joueurs se décalent d'une place vers la droite.", titre: "Monde parallèle" },
    { categorie: Categorie.chaos, cycle: "Solidarité", description: "Avance de deux cases tous les joueurs sauf le premier.", titre: "Il fait une sieste" },
    { categorie: Categorie.chaos, cycle: "Solidarité", description: "Avance le dernier joueur de trois cases.", titre: "Il a vu un fantôme" },
    { categorie: Categorie.chaos, cycle: "Solidarité", description: "Avance tous les joueurs en arrière de toi d'une case.", titre: "Parfum alléchant" },
    { categorie: Categorie.chaos, cycle: "Solidarité", description: "Déplace le premier joueur sur la case du dernier joueur.", titre: "On veut jouer plus longtemps" },
    { categorie: Categorie.chaos, cycle: "Solidarité", description: "Tous les joueurs font la prochaine conséquence.", titre: "Communisme" },
    { categorie: Categorie.chaos, cycle: "Solidarité", description: "Tous les joueurs reculent de deux cases.", titre: "Retour dans le temps" },

    { categorie: Categorie.defi, cycle: "Langage", description: "Communique seulement en utilisant plusieurs cris d'animaux jusqu'à ton prochain tour." },
    { categorie: Categorie.defi, cycle: "Langage", description: "Ne dis plus un mot jusqu'à ton prochain tour.", titre: "Silence" },
    { categorie: Categorie.defi, cycle: "Langage", description: "Parle avec un accent français jusqu'à ton prochain tour.", titre: "Alors du coup" },
    { categorie: Categorie.defi, cycle: "Langage", description: "Parle en anglais jusqu'à ton prochain tour." },
    { categorie: Categorie.defi, cycle: "Loup-Garou", description: "Fais 5 push-ups.", titre: "Tu te prépares à kidnapper ton crush" },
    { categorie: Categorie.defi, cycle: "Loup-Garou", description: "Le chaperon rouge prend du temps à s'en venir. Va faire la chaise pendant 20 secondes." },
    { categorie: Categorie.defi, cycle: "Loup-Garou", description: "Montre ta supériorité et ton statut d'alpha en restant debout jusqu'à ton prochain tour.", titre: "Chef.fe de la meute" },
    { categorie: Categorie.defi, cycle: "Loup-Garou", description: "Va te cacher dans la grotte (sous la table) jusqu'à ton prochain tour.", titre: "Le chasseur est sorti" },
    { categorie: Categorie.defi, cycle: "Mimes", description: "Buffy contre les vampires." },
    { categorie: Categorie.defi, cycle: "Mimes", description: "Lancer du papier de toilette sur une maison." },
    { categorie: Categorie.defi, cycle: "Mimes", description: "Le film l'Exorciste." },
    { categorie: Categorie.defi, cycle: "Mimes", description: "Le film Twilight." },
    { categorie: Categorie.defi, cycle: "Mimes", description: "Nick Quasi-Sans-Tête." },
    { categorie: Categorie.defi, cycle: "Mimes", description: "Une citrouille avec une chandelle à l'intérieur." },
    { categorie: Categorie.defi, cycle: "Partage", description: "Emprunte un accessoire de quelqu'un d'autre jusqu'à ton prochain tour." },
    { categorie: Categorie.defi, cycle: "Partage", description: "Mets les bas de quelqu'un d'autre jusqu'à ton prochain tour." },
    { categorie: Categorie.defi, cycle: "Partage", description: "Porte le chapeau de quelqu'un d'autre jusqu'à ton prochain tour.", titre: "Tu deviens chauve" },
    { categorie: Categorie.defi, cycle: "Social", description: "Amène un bonbon à Léa." },
    { categorie: Categorie.defi, cycle: "Social", description: "Amène un rouleau de Rockets à Charles-André.", titre: "Vers d'autres cieux" },
    { categorie: Categorie.defi, cycle: "Social", description: "Nomme correctement tous les joueurs à la table." },
    { categorie: Categorie.defi, cycle: "Social", description: "Trouve un.e non-joueur.euse et viens nous le.a présenter en quelques phrases.", titre: 'Connais-tu Alex?' },
    { categorie: Categorie.defi, cycle: "Social", description: "Va changer la chanson qui joue et mets celle de ton choix. Chante-la (la table doit t'entendre).", titre: "Perce-oreilles" },
    { categorie: Categorie.defi, cycle: "Trouvez Charlie", description: "Trouve un non-joueur qui a un chat chez lui." },
    { categorie: Categorie.defi, cycle: "Trouvez Charlie", description: "Trouve un non-joueur qui a une imprimante 3D chez lui.", titre: "Une bonne impression" },
    { categorie: Categorie.defi, cycle: "Trouvez Charlie", description: "Trouve un non-joueur qui est encore aux études." },
    { categorie: Categorie.defi, cycle: "Trouvez Charlie", description: "Trouve un non-joueur qui est venu en autobus." },
    { categorie: Categorie.defi, cycle: "Trouvez Charlie", description: "Trouve un non-joueur qui est venu en voiture." },

    { categorie: Categorie.verite, cycle: "Halloween", description: "Qu'est-ce que la maison de riches donnait quand tu passais l'Halloween\u202f?" },
    { categorie: Categorie.verite, cycle: "Halloween", description: "Quel bonbon espérais-tu obtenir quand tu passais l'Halloween\u202f?" },
    { categorie: Categorie.verite, cycle: "Halloween", description: "Quel bonbon ne mangeais-tu jamais quand tu passais l'Halloween\u202f?" },
    { categorie: Categorie.verite, cycle: "Halloween", description: "Quel genre de sac utilisais-tu quand tu passais l'Halloween\u202f?" },
    { categorie: Categorie.verite, cycle: "Halloween", description: "Tu as passé l'Halloween jusqu'à quel âge\u202f?" },
    { categorie: Categorie.verite, cycle: "Informations", description: "Comment connais-tu les hôtes de l'événement\u202f?" },
    { categorie: Categorie.verite, cycle: "Informations", description: "Quel est le dernier film que tu as vu\u202f?" },
    { categorie: Categorie.verite, cycle: "Informations", description: "Quelle est la dernière chose que tu as commencé à apprendre\u202f?" },
    { categorie: Categorie.verite, cycle: "Informations", description: "Raconte-nous ta journée d'hier." },
    { categorie: Categorie.verite, cycle: "Mal", description: "Dans quel cercle de l'enfer es-tu le plus probable d'aller\u202f?" },
    { categorie: Categorie.verite, cycle: "Mal", description: "Pour quelle raison irais-tu en prison\u202f?" },
    { categorie: Categorie.verite, cycle: "Mal", description: "Préférerais-tu mourir ou devenir un loup-garou\u202f?" },
    { categorie: Categorie.verite, cycle: "Mal", description: "Préférerais-tu mourir ou devenir un vampire\u202f?" },
    { categorie: Categorie.verite, cycle: "Mal", description: "Préférerais-tu mourir ou devenir un zombie\u202f?" },
    { categorie: Categorie.verite, cycle: "Mal", description: "Quelle est ton incantation préférée\u202f?" },
    { categorie: Categorie.verite, cycle: "Mal", description: "Qui est ton tueur préféré\u202f?" },
    { categorie: Categorie.verite, cycle: "Mal", description: "Selon toi, quelle est la pire malédiction que quelqu'un pourrait recevoir\u202f?" },
    { categorie: Categorie.verite, cycle: "Mal", description: "Si on remplaçait tous les humains par des copies toi, quand se produirait le premier meurtre\u202f?" },
    { categorie: Categorie.verite, cycle: "Mal", description: "Si tu devais tuer quelqu'un, quelle arme utiliserais-tu\u202f?" },
    { categorie: Categorie.verite, cycle: "Marie/tue/fourre", description: ["Godzilla", "Mothra", "King Kong"], titre: "Animaux" },
    { categorie: Categorie.verite, cycle: "Marie/tue/fourre", description: ["Jigsaw (la marionette)", "Chucky", "Un Mogwai/gremlin"], titre: "Jouets" },
    { categorie: Categorie.verite, cycle: "Marie/tue/fourre", description: ["Leatherface", "Jason Voorhees", "Michael Myer"], titre: "Masques" },
    { categorie: Categorie.verite, cycle: "Marie/tue/fourre", description: ["Patrick Bateman", "Sweeney Todd", "Hannibal Lecter"], titre: "Sigmas" },
    { categorie: Categorie.verite, cycle: "Marie/tue/fourre", description: ["Un loup-garou", "Un vampire", "Un zombie"] },
    { categorie: Categorie.verite, cycle: "Mise en situation", description: "Lors d'un rituel occulte, qui manifesterais-tu, et que lui demanderais-tu\u202f?" },
    { categorie: Categorie.verite, cycle: "Mise en situation", description: "Si tu étais dans un film d'horreur, quel rôle aurais-tu\u202f?" },
    { categorie: Categorie.verite, cycle: "Mise en situation", description: "Si tu étais un fantôme, qu'hanterais-tu\u202f?" },
    { categorie: Categorie.verite, cycle: "Mise en situation", description: "Tu reçois un bébé zombie, que tu ne peux pas donner. Que fais-tu\u202f?" },
    { categorie: Categorie.verite, cycle: "Mise en situation", description: "Un tueur en série est dans ta maison/appartement. Où vas-tu te réfugier\u202f?" },
    { categorie: Categorie.verite, cycle: "Mise en situation", description: "Une succube apparaît devant toi et désire ton «\u00a0«\u00a0essence\u00a0»\u00a0». Lui donnes-tu\u202f?" },
    { categorie: Categorie.verite, cycle: "Peur", description: "Quel animal te fait le plus peur\u202f?" },
    { categorie: Categorie.verite, cycle: "Peur", description: "Quel film t'a le plus traumatisé quand tu étais enfant\u202f?" },
    { categorie: Categorie.verite, cycle: "Peur", description: "Quel monstre tes parents utilisaient-ils pour te faire peur\u202f?" },
    { categorie: Categorie.verite, cycle: "Peur", description: "Quelle est une de tes phobies les plus irrationnelles\u202f?" },
];

export default cartes;